name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Wait for Vercel preview deployment
        id: get-preview-url
        run: |
          echo "🔍 Waiting for Vercel deployment via API..."

          for i in {1..30}; do
            RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
              "https://api.vercel.com/v6/deployments?projectId=${{ secrets.VERCEL_PROJECT_ID }}&state=READY")

            DEPLOYMENT_URL=$(echo "$RESPONSE" | jq -r \
              '.deployments[] | select(.meta.githubCommitRef=="'${{ github.head_ref }}'") | .url' | head -n 1)

            if [ -n "$DEPLOYMENT_URL" ]; then
              echo "✅ Deployment ready: https://$DEPLOYMENT_URL"
              echo "DEPLOYMENT_URL=https://$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
              break
            else
              echo "⏳ Not ready yet... retrying in 5s"
              sleep 5
            fi
          done

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests on live preview
        env:
          BASE_URL: ${{ steps.get-preview-url.outputs.DEPLOYMENT_URL }}
        run: |
          echo "🌐 Running tests on $BASE_URL"
          npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
